/**
 * Log type - either "application" or "system"
 */
export type LogType = 'application' | 'system';

/**
 * Log level
 */
export type LogLevel = 'INFO' | 'DEBUG' | 'WARNING' | 'ERROR' | 'CRITICAL';

/**
 * Request information associated with a log
 */
export interface RequestInfo {
    userAgent?: string;
    url?: string;
    queryString?: string;
    host?: string;
    ip?: string;
    referer?: string;
    browser?: string;
    os?: string;
    origin?: string;
}

/**
 * Log interface representing a log document in Firestore
 */
export interface Log {
    _id?: string; // Firestore document ID
    level: string;
    environment: string;
    request?: RequestInfo;
    projectId: string; // Project slug identifier
    projectObjectId: string; // Firestore document ID of the project
    message: string;
    stackTrace: Array<Record<string, any>>;
    rawStackTrace?: string; // Optional string representation of the original stack trace
    details: Record<string, any>;
    detailString: string | null; // Stringified version of details
    timestampMS: number; // UNIX timestamp in milliseconds
    createdAt: Date;
    hostname?: string; // Optional hostname
    logType: LogType; // Mandatory log type: "application" or "system"
}

/**
 * Log creation input
 */
export interface CreateLogInput {
    level: string;
    environment: string;
    projectId: string;
    message: string;
    request?: RequestInfo;
    logType: LogType; // Mandatory log type: "application" or "system"
    stackTrace?: Array<Record<string, any>>;
    rawStackTrace?: string; // Optional string representation of the original stack trace
    details?: Record<string, any>;
    detailString?: string | null; // Stringified version of details - will be generated by API
    timestampMS?: number; // Optional - will be generated by API if not provided
    hostname?: string; // Optional hostname
}

/**
 * Log query parameters for filtering and pagination
 */
export interface LogQueryParams {
    page?: number;
    pageSize?: number;
    level?: string;
    environment?: string;
}

/**
 * Message match type for filtering logs
 */
export type MessageMatchType = 'contains' | 'startsWith' | 'endsWith';

/**
 * Message condition (single phrase with match type)
 */
export interface MessageCondition {
    phrase: string;
    matchType: MessageMatchType;
}

/**
 * Document filter (searches across message, rawStackTrace, and detailString)
 */
export interface DocFilter {
    phrase: string;
    matchType: MessageMatchType;
}

/**
 * Message filter with AND/OR logic
 */
export interface MessageFilter {
    operator: 'AND' | 'OR';
    conditions: MessageCondition[];
}

/**
 * Request body for querying logs
 */
export interface QueryLogsRequest {
    page?: number;
    pageSize?: number;
    level?: string | string[];
    environment?: string | string[];
    logType?: string; // Single log type filter: "application" or "system"
    hostname?: string | string[]; // Filter by hostname(s) - can be a single string or array of strings
    startTime?: number; // Unix timestamp in milliseconds - start of time range
    endTime?: number; // Unix timestamp in milliseconds - end of time range
    docFilter?: DocFilter;
    message?: MessageFilter;
    stackTrace?: MessageFilter;
    details?: MessageFilter;
}
